name: point-cloud
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36h9f0ad1d_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.64.2=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=64.2=he1b5a44_1
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hdb11119_1
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcxx=10.0.0=0
  - libcxxabi=10.0.0=0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py36hb8e4980_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py36h7314795_1
  - olefile=0.46=py_0
  - openssl=1.1.1f=h516909a_0
  - pandas=1.0.3=py36h830a2c2_1
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py36h8328e55_1
  - pip=9.0.3=py36_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyntcloud=0.1.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - qt=5.12.5=hd8c4c69_1
  - scikit-learn=0.22.2.post1=py36hcdab131_0
  - scipy=1.4.1=py36h2d22cac_3
  - setuptools=46.1.1=py36h9f0ad1d_0
  - six=1.14.0=py_1
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py36h8c4c3a4_1
  - wheel=0.34.2=py_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h516909a_1002
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_2
  - libedit=3.1.20181209=hc058e9b_0
  - ncurses=6.2=he6710b0_0
  - python=3.6.10=hcf32534_1
  - readline=8.0=h7b6447c_0
  - sqlite=3.31.1=h7b6447c_0
  - pip:
    - appnope==0.1.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bitarray==1.2.1
    - bleach==3.1.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter-client==6.1.3
    - jupyter-core==4.6.3
    - lxml==4.5.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - more-itertools==8.2.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.0.3
    - open3d==0.9.0.0
    - packaging==20.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - plyfile==0.7.2
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - py==1.8.1
    - pyang==2.2.1
    - pyangbind-brcd==0.6.14
    - pybind==0.1.35
    - pygments==2.6.1
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyrsistent==0.16.0
    - pytest==5.4.1
    - pyzmq==19.0.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0
prefix: /opt/conda/envs/point-cloud

